services:
  lsp-c:
    build:
      context: ./docker/lsp/clangd
      dockerfile: Dockerfile
    image: lsp-c:latest
    container_name: lsp-c
    restart: always
    ports:
      - "4594:3000"
    networks:
      - judge4c
    healthcheck:
      test: ["CMD-SHELL", "nc -zv localhost 3000"]
      interval: 10s
      timeout: 5s
      retries: 5

  lsp-cpp:
    build:
      context: ./docker/lsp/clangd
      dockerfile: Dockerfile
    image: lsp-cpp:latest
    container_name: lsp-cpp
    restart: always
    ports:
      - "4595:3000"
    networks:
      - judge4c
    healthcheck:
      test: ["CMD-SHELL", "nc -zv localhost 3000"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  judge4c:
    name: judge4c
